### ISSUE TITLE
This product is currently out of stock and unavailable.

### ISSUE THREAD

**Issue by ndpa** [HasteDesign/Registrations-for-WooCommerce#28] opened 2018-06-01 00:41 UTC
Not sure if there is an issue with this plugin, but I am now getting the text "This product is currently out of stock and unavailable." on all of my "Registration" products in Woocommerce.

There was a recent update in Woocommerce (I believe) and I had to update some of the templates for my Theme, but it seems all my products are working except for the Registration ones.

I have played around with all of the inventory settings and "Enable stock management at product level" combinations, but the product on the front end (and sometimes in my list of products on the back end) says "Out of Stock".

I really like and need this plugin too :-)

**Comment by allysonsouza** [comment] 2018-06-01 01:31
Hi @ndpa , I'm working right now to fix this issue, it's caused by an update in WC_Product_Variable class change in WooCommerce 3.4 release. Now it's fixed here in Github, but I'm just doing some tests and then will release it tomorrow in official repository

**Comment by allysonsouza** [comment] 2018-06-03 16:53
Fixed in release 2.0.4

**Closed by allysonsouza** 2018-06-03 16:53 UTC
Labels: bug
